In [28]:
import pandas as pd

csv_1 = pd.read_csv("customers-100.csv")
csv_1

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [22]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

# Read the CSV file into a DataFrame
df = pd.read_csv("customers-100.csv")
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [25]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('CoffeeChain-SimplifiedData.csv')
df

,Product Id,Product Type,Product,Type,Market Size,Market,State,Budget Sales,Budget Profit,Cogs,Profit,Sales,Total Expenses,Date
0,1,Coffee,Amaretto,Regular,Major Market,Central,Colorado,220,100,89,94,219,36,01-01-2010 00:00
1,2,Coffee,Columbian,Regular,Major Market,Central,Colorado,190,80,83,68,190,39,01-01-2010 00:00
2,3,Coffee,Decaf Irish Cream,Decaf,Major Market,Central,Colorado,240,110,95,101,234,38,01-01-2010 00:00
3,13,Tea,Green Tea,Regular,Major Market,Central,Colorado,80,30,44,30,100,26,01-01-2010 00:00
4,5,Espresso,Caffe Mocha,Regular,Major Market,Central,Colorado,150,70,54,54,134,26,01-01-2010 00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4243,4,Espresso,Caffe Latte,Regular,Small Market,West,Washington,50,20,24,19,60,19,01-12-2011 00:00
4244,5,Espresso,Caffe Mocha,Regular,Small Market,West,Washington,140,30,65,34,155,57,01-12-2011 00:00
4245,6,Espresso,Decaf Espresso,Decaf,Small Market,West,Washington,170,60,80,76,188,45,01-12-2011 00:00
4246,2,Coffee,Columbian,Regular,Small Market,West,Washington,200,80,72,86,188,46,01-12-2011 00:00
4247,3,Coffee,Decaf Irish Cream,Decaf,Small Market,West,Washington,290,50,105,30,266,125,01-12-2011 00:00

In [26]:
import pandas as pd

# Sample data as a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}

# Create DataFrame
df = pd.DataFrame(data)

# Show DataFrame output
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris

In [27]:
import pandas as pd

# Sample data as a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}

# Create DataFrame
df = pd.DataFrame(data)

# Save DataFrame to CSV file
df.to_csv('output.csv', index=False)